### ISSUE TITLE
Upgrade to react-docgen@v5.0.0-beta.1

### ISSUE THREAD

**Issue by 7rulnik** [storybookjs/babel-plugin-react-docgen#72]
react-docgen@v5.0.0-beta.1 was [released](https://github.com/reactjs/react-docgen/releases) few months ago. Now it's smaller, supports TS, forwardRef and others.

**Comment by josias-r** [comment]
very welcome here as well, since current alternatives are lacking features

**Comment by shilman** [comment]
@danielduan i'm also interested in this as part of [Storybook Docs](https://medium.com/storybookjs/storybook-docspage-e185bc3622bf) and since i also manage all the SB releases i'd be happy to work together to figure out the best way to get this out.

what do you think about:
1. upgrading this package
2. releasing this package as a beta
3. incorporating the beta package into `5.3-alpha` as soon as 5.2 ships (very soon)

hopefully things can during the 5.3 release cycle, and by the time we're ready to go live, we can release the latest `react-docgen` with confidence. what do you think?

**Comment by josias-r** [comment]
I tried it locally and I didn't experience any errors, simply updating it should be all the work needed ^^

**Comment by danielduan** [comment]
My apologies for taking so long, I published a prerelease version `babel-plugin-react-docgen@4.0.0-beta.1` under the `prerelease` tag.

I haven't had the chance to get my dev environment up to speed with the latest Storybook development so please let me know if this works. @shilman @josias-r @7rulnik

**Comment by shilman** [comment]
@danielduan I'm considering upgrading Storybook 5.3-alpha to use this prerelease. 5.3's target release date is Jan 7 ... any thoughts on that, one way or the other?

**Comment by danielduan** [comment]
@shilman I think it's a toss up without knowing react-docgen's release schedule. The new features in 4.0.0 is definitely worth upgrading for if we're okay with testing out the stability and reliability.

Perhaps we throw it into our prerelease builds and if things go wrong, we remove it before the full release? If it goes well, we just keep the beta version?

**Comment by shilman** [comment]
@danielduan Cool. I'm gonna do a release with 3.2 now, just so there's one out there, and then we can upgrade to 4.0 next.

**Comment by josias-r** [comment]
react-docgen@v5.0.0 has just been released 🥳

**Comment by danielduan** [comment]
I'm on vacation for the next few days, if anyone wants to open a PR for it, would help me out a lot. Otherwise, I will get an update out sometime hopefully late next week.

**Comment by shilman** [comment]
@danielduan I'll try to take a look at it & will post here
