### ISSUE TITLE
"Component".__docgenInfo no available  on 4.2.0

### ISSUE THREAD

**Issue by kivervinicius** [storybookjs/babel-plugin-react-docgen#90]
I update to 4.2.0, but, __docgenInfo no work anymore, in 4.1.0 work

**Comment by jimmyandrade** [comment]
> I update to 4.2.0, but, __docgenInfo no work anymore, in 4.1.0 work

@kivervinicius hello, thanks for reporting this issue.

Could you help us editing your issue with a more clear description of what the bug is, including steps to reproduce the behavior, the expected behavior and current behavior (with screenshots and/or some error log).

A minimal reproduction would be good too, together with some environment info, like:

- OS: [e.g. iOS]
- Node.js version: [e.g. v12.17.0]
- NPM version: [e.g. 6.14.4]

Thank you 😄

**Comment by kivervinicius** [comment]
@jimmyandrade today i updated the version available in npm and my project no longer sees the __docgen property, i will mount an example

**Comment by jimmyandrade** [comment]
> @jimmyandrade today i updated the version available in npm and my project no longer sees the __docgen property, i will mount an example

@kivervinicius I understand and I'm sorry for that. I'll wait for the example so that I can contribute in some way.
Thank you :)

**Comment by shilman** [comment]
@phated any thoughts on this?

**Comment by kivervinicius** [comment]
#91 Related problem, im my case, the problem ocurrent with handlers

` ["babel-plugin-react-docgen",
        {
            "handlers:": [
                "react-docgen-deprecation-handler"
            ]
        }]
`
